const labels={B3:'B3 地下3階',B2:'B2 地下2階',B1:'B1 地下1階','1F 本館':'1F 本館','2F 本館':'2F 本館'};
const slugs={B3:'b3.html',B2:'b2.html',B1:'b1.html','1F 本館':'1f.html','2F 本館':'2f.html'};
const floor=document.body.dataset.floor;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function nav(){return Object.keys(labels).map(f=>`<a class="${f===floor?'active':''}" href="${slugs[f]}">${labels[f]}</a>`).join('')}
function wikiLink(w){if(w.rank!=='S')return '';const query=encodeURIComponent(`${w.title} ${w.artist}`);return `<a class="wiki" href="https://ja.wikipedia.org/wiki/Special:Search?search=${query}&go=Go" target="_blank" rel="noopener noreferrer">Wikipediaで見る <span aria-hidden="true">↗</span></a>`}
function toggleCard(summary){const details=summary.nextElementSibling;const opening=summary.getAttribute('aria-expanded')!=='true';summary.setAttribute('aria-expanded',String(opening));details.hidden=!opening}
function card(w){const rc=w.rank?`<span class="rank ${w.rank.toLowerCase()}">${esc(w.rank)}</span>`:'';return `<article class="work"><button class="work-summary" type="button" aria-expanded="false"><span class="num">${esc(w.number)}</span><span class="work-heading"><span class="work-title">${esc(w.title||'題名記載なし')}</span><span class="artist">${esc(w.artist||'作者名記載なし')}</span></span>${rc}<span class="chevron" aria-hidden="true">⌄</span></button><div class="details" hidden><b>${esc(w.museum||'所蔵先記載なし')}</b>${w.place?`<br>${esc(w.place)}`:''}${w.memo?`<br>メモ：${esc(w.memo)}`:''}${wikiLink(w)}</div></article>`}
function render(){const q=document.querySelector('.search').value.trim().toLowerCase();const rank=document.querySelector('.rank-filter').value;const all=window.ARTWORKS.filter(w=>w.floor===floor);const rows=all.filter(w=>(!rank||w.rank===rank)&&(!q||[w.number,w.artist,w.title,w.museum,w.place,w.memo].join(' ').toLowerCase().includes(q)));document.querySelector('.count').innerHTML=`<strong>${rows.length}</strong> / ${all.length}作品`;document.querySelector('.works').innerHTML=rows.length?rows.map(card).join(''):'<p class="empty">条件に一致する作品はありません。</p>'}
document.querySelector('.floor-nav').innerHTML=nav();document.querySelector('.page-title').textContent=labels[floor];document.querySelector('.search').addEventListener('input',render);document.querySelector('.rank-filter').addEventListener('change',render);document.querySelector('.works').addEventListener('click',e=>{const summary=e.target.closest('.work-summary');if(summary)toggleCard(summary)});render();
